### ISSUE TITLE
Variance Question

### ISSUE THREAD

**Issue by RbotJ** [JRomainG/GD32F130K6-hoverboard-hack#4]
Will this work with an MM32F031 chip? Or could you point me to the right place? I have 4 hoverboards I'd like to repurpose with these split boards.
Thank you.
![Mainboard A](https://user-images.githubusercontent.com/33506284/188664375-8a24871f-3bf5-436d-b119-bd89bb31332e.jpg)
![Chip](https://user-images.githubusercontent.com/33506284/188664388-4a320bdc-53b0-405e-82ad-6422aa38df4d.jpg)

**Comment by JRomainG** [comment]
As this isn't the exact same chip, the pins are probably different. From a quick search, it seems like [this](http://47.103.60.28:8090/userfiles/images/MM32F031XiLieWenDang/DS_MM32F031xx_n_V1.11_EN.pdf) might be the right datasheet for your chip, which can tell you about the pins. From there, you can probably adapt the steps described in this repository to your chip to unlock it.

Getting a working firmware is another issue though (see #2). If you need help with that, you can probably reach out to the folks on the [Hooover Telegram channel](https://t.me/joinchat/BHWO_RKu2LT5ZxEkvUB8uw).
